/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    projects: Project;
    skills: Skill;
    education: Education;
    certifications: Certification;
    experience: Experience;
    media: Media;
    profile: Profile;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    profile: ProfileSelect<false> | ProfileSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Authorized administrators who can securely manage SyedOS content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The administrator’s professional display name.
   */
  name: string;
  /**
   * Controls access to protected SyedOS administration features.
   */
  role: 'super-admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Manage the projects displayed across the SyedOS professional portfolio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  /**
   * The professional name displayed on project cards and detail pages.
   */
  title: string;
  /**
   * Automatically generated from the project title. Example: syedai-assistant
   */
  slug: string;
  projectType: 'full-stack' | 'ai' | 'cloud-devops' | 'frontend' | 'backend' | 'academic' | 'other';
  developmentStatus: 'planning' | 'in-development' | 'completed' | 'maintained' | 'archived';
  /**
   * A concise project summary used on portfolio cards and previews.
   */
  shortDescription: string;
  /**
   * A detailed professional explanation of the project, its purpose, and its outcome.
   */
  fullDescription: string;
  technologies: {
    name: string;
    category: 'frontend' | 'backend' | 'database' | 'ai' | 'cloud' | 'devops' | 'testing' | 'tool' | 'other';
    id?: string | null;
  }[];
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  responsibilities?:
    | {
        description: string;
        id?: string | null;
      }[]
    | null;
  githubURL?: string | null;
  liveURL?: string | null;
  documentationURL?: string | null;
  /**
   * Temporary image path field. It will later be upgraded to Payload Media uploads.
   */
  coverImageURL?: string | null;
  /**
   * Describe the image for accessibility and search engines.
   */
  coverImageAlt?: string | null;
  /**
   * Display this project prominently on the homepage.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear before higher numbers.
   */
  displayOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage the technical skills displayed throughout the SyedOS professional portfolio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  _order?: string | null;
  /**
   * The professional technology or skill name displayed across the portfolio.
   */
  name: string;
  /**
   * Automatically generated from the skill name. Example: next-js
   */
  slug: string;
  category:
    | 'programming-language'
    | 'frontend'
    | 'backend'
    | 'database'
    | 'ai'
    | 'cloud'
    | 'devops'
    | 'testing'
    | 'cybersecurity'
    | 'tool'
    | 'soft-skill'
    | 'other';
  proficiency: 'beginner' | 'intermediate' | 'advanced' | 'professional';
  /**
   * Used for skill indicators. Enter a value from 0 to 100.
   */
  proficiencyPercentage: number;
  /**
   * Approximate practical experience with this skill.
   */
  yearsOfExperience?: number | null;
  /**
   * A concise explanation of how this skill is used in your work.
   */
  shortDescription: string;
  /**
   * Optional icon identifier, such as nextjs, typescript, docker, or postgres.
   */
  iconName?: string | null;
  capabilities?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Connect this skill to projects that demonstrate practical experience.
   */
  relatedProjects?: (number | Project)[] | null;
  learningSources?:
    | {
        title: string;
        provider?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display this skill prominently on the homepage or skills overview.
   */
  featured?: boolean | null;
  /**
   * Lower values appear before higher values.
   */
  displayOrder: number;
  /**
   * Controls the visual accent used for this skill in the portfolio.
   */
  accentStyle?: ('blue' | 'cyan' | 'teal' | 'violet' | 'amber' | 'emerald') | null;
  /**
   * Examples: Core Skill, Currently Learning, Certified, or Advanced.
   */
  badgeLabel?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage academic qualifications, institutions, achievements, coursework, and education details displayed on SyedOS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: number;
  _order?: string | null;
  /**
   * Enter the complete official name of the school, college, university, or training institution.
   */
  institution: string;
  /**
   * Automatically generated from the qualification and institution.
   */
  slug: string;
  educationLevel:
    | 'secondary-school'
    | 'higher-secondary'
    | 'diploma'
    | 'undergraduate'
    | 'postgraduate'
    | 'doctorate'
    | 'professional-certification'
    | 'other';
  qualification: string;
  fieldOfStudy?: string | null;
  /**
   * Optional specialization, concentration, branch, or major.
   */
  specialization?: string | null;
  /**
   * Enter the university name when the institution is an affiliated college.
   */
  university?: string | null;
  location?: string | null;
  institutionWebsite?: string | null;
  startYear: number;
  endYear?: number | null;
  /**
   * Enable this when the qualification is still in progress.
   */
  currentlyStudying?: boolean | null;
  expectedCompletion?: string | null;
  resultType?: ('cgpa' | 'gpa' | 'percentage' | 'grade' | 'pass' | 'not-applicable') | null;
  result?: string | null;
  /**
   * Optional grading scale used by the institution.
   */
  resultScale?: string | null;
  academicStanding?:
    ('distinction' | 'first-class' | 'second-class' | 'pass' | 'in-progress' | 'not-applicable') | null;
  /**
   * Explain the programme, academic focus, practical work, and its relevance to your professional goals.
   */
  summary: string;
  coursework?:
    | {
        courseName: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  achievements?:
    | {
        title: string;
        description?: string | null;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  activities?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Connect this education record to relevant technical and professional skills.
   */
  relatedSkills?: (number | Skill)[] | null;
  /**
   * Connect academic projects completed during this qualification.
   */
  relatedProjects?: (number | Project)[] | null;
  /**
   * Feature this qualification prominently on the portfolio.
   */
  featured?: boolean | null;
  /**
   * Lower values appear before higher values.
   */
  displayOrder: number;
  logoPath?: string | null;
  /**
   * Describe the logo for accessibility and search engines.
   */
  logoAlt?: string | null;
  /**
   * Optional public URL for the certificate, marks memo, credential, or verification page.
   */
  certificateURL?: string | null;
  badgeLabel?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage professional certifications, course credentials, verification details, skills, and presentation settings displayed on SyedOS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  _order?: string | null;
  /**
   * Enter the official certification, professional credential, course, or programme title.
   */
  title: string;
  /**
   * Automatically generated from the certification title.
   */
  slug: string;
  issuer: string;
  certificationType:
    | 'professional-certification'
    | 'professional-certificate'
    | 'course-certificate'
    | 'specialization'
    | 'skill-badge'
    | 'workshop'
    | 'internship'
    | 'participation'
    | 'other';
  issuerWebsite?: string | null;
  /**
   * Summarize the programme, skills covered, assessment, practical work, and professional relevance.
   */
  description: string;
  /**
   * Optional official credential or certificate identifier.
   */
  credentialID?: string | null;
  /**
   * Public verification URL supplied by the issuing organization.
   */
  credentialURL?: string | null;
  issueDate: string;
  expiryDate?: string | null;
  doesNotExpire?: boolean | null;
  credentialStatus: 'completed' | 'in-progress' | 'expired' | 'planned';
  /**
   * Enter the current progress percentage from 0 to 100.
   */
  completionProgress?: number | null;
  estimatedHours?: number | null;
  score?: string | null;
  /**
   * Connect the credential to relevant skills already stored in SyedOS.
   */
  skillsCovered?: (number | Skill)[] | null;
  /**
   * Connect projects that demonstrate knowledge gained from this certification.
   */
  relatedProjects?: (number | Project)[] | null;
  learningOutcomes?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Describe quizzes, examinations, graded assignments, projects, or practical assessments.
   */
  assessmentDetails?: string | null;
  instructors?:
    | {
        name: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Feature this credential prominently on the homepage or certifications page.
   */
  featured?: boolean | null;
  /**
   * Lower values appear before higher values.
   */
  displayOrder: number;
  certificateImagePath?: string | null;
  /**
   * Describe the certificate image for accessibility and search engines.
   */
  certificateImageAlt?: string | null;
  issuerLogoPath?: string | null;
  issuerLogoAlt?: string | null;
  badgeLabel?: string | null;
  accentStyle?: ('blue' | 'cyan' | 'teal' | 'violet' | 'amber' | 'emerald') | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage internships, employment, freelance work, academic experience, leadership roles, and professional responsibilities displayed on SyedOS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: number;
  _order?: string | null;
  /**
   * Enter the official role, internship title, job title, leadership position, or responsibility.
   */
  role: string;
  /**
   * Automatically generated from the role and organization.
   */
  slug: string;
  organization: string;
  experienceType:
    | 'internship'
    | 'full-time'
    | 'part-time'
    | 'freelance'
    | 'contract'
    | 'academic-project'
    | 'leadership'
    | 'volunteer'
    | 'training'
    | 'other';
  location?: string | null;
  workMode?: ('onsite' | 'remote' | 'hybrid') | null;
  organizationWebsite?: string | null;
  /**
   * Summarize the role, major responsibilities, technologies used, and professional relevance.
   */
  summary: string;
  startDate: string;
  endDate?: string | null;
  currentlyWorking?: boolean | null;
  /**
   * Optional human-readable duration shown on the public portfolio.
   */
  durationLabel?: string | null;
  responsibilities?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  achievements?:
    | {
        title: string;
        description?: string | null;
        metric?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Connect this experience to the relevant skills stored in SyedOS.
   */
  technologies?: (number | Skill)[] | null;
  /**
   * Connect projects completed or developed during this experience.
   */
  relatedProjects?: (number | Project)[] | null;
  teamSize?: number | null;
  supervisor?: {
    name?: string | null;
    role?: string | null;
    organization?: string | null;
  };
  /**
   * Optional public certificate, internship letter, or verification link.
   */
  certificateURL?: string | null;
  projectURL?: string | null;
  organizationLogoPath?: string | null;
  organizationLogoAlt?: string | null;
  supportingDocuments?:
    | {
        title: string;
        url: string;
        documentType?:
          ('certificate' | 'offer-letter' | 'completion-letter' | 'recommendation' | 'project-report' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Feature this experience prominently on the homepage or experience page.
   */
  featured?: boolean | null;
  /**
   * Lower values appear before higher values.
   */
  displayOrder: number;
  badgeLabel?: string | null;
  accentStyle?: ('blue' | 'cyan' | 'teal' | 'violet' | 'amber' | 'emerald') | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage project images, profile photos, institution logos, certificates, resume files, and other media used across SyedOS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Enter a clear internal title for identifying this file in the CMS.
   */
  title: string;
  /**
   * Describe the image or document for accessibility and search engines.
   */
  alt: string;
  /**
   * Optional public caption or supporting context for this media item.
   */
  caption?: string | null;
  mediaType:
    | 'profile-photo'
    | 'project-cover'
    | 'project-screenshot'
    | 'institution-logo'
    | 'organization-logo'
    | 'issuer-logo'
    | 'certificate'
    | 'resume'
    | 'document'
    | 'general';
  visibility: 'public' | 'private' | 'unlisted';
  /**
   * Mark this as a preferred file for featured sections or primary display.
   */
  featured?: boolean | null;
  /**
   * Lower values appear before higher values.
   */
  displayOrder: number;
  /**
   * Optional photographer, creator, institution, or source attribution.
   */
  credit?: string | null;
  /**
   * Optional ownership or usage-rights information.
   */
  copyrightNotice?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Private CMS notes for file usage, replacement plans, or verification status.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage the main professional identity, biography, contact details, career preferences, social links, and personal presentation used across SyedOS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: number;
  /**
   * Enter the professional name displayed throughout the portfolio.
   */
  fullName: string;
  /**
   * Automatically generated from the full name.
   */
  slug: string;
  professionalTitle: string;
  /**
   * A shorter title for compact cards, metadata, and navigation.
   */
  shortTitle?: string | null;
  /**
   * A concise professional introduction for the homepage hero section.
   */
  headline: string;
  /**
   * A brief professional summary for cards, homepage sections, and metadata.
   */
  shortBio: string;
  /**
   * A detailed biography for the About page, including education, interests, projects, and career direction.
   */
  fullBio: string;
  location?: string | null;
  nationality?: string | null;
  languages?:
    | {
        language: string;
        proficiency: 'basic' | 'conversational' | 'professional' | 'native-bilingual';
        id?: string | null;
      }[]
    | null;
  /**
   * Describe the type of opportunities, responsibilities, technologies, and professional growth you are pursuing.
   */
  careerObjective: string;
  careerInterests?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  preferredRoles?:
    | {
        role: string;
        id?: string | null;
      }[]
    | null;
  availabilityStatus:
    'open-to-internships' | 'open-to-part-time' | 'open-to-full-time' | 'open-to-freelance' | 'not-available';
  preferredWorkModes?: ('remote' | 'hybrid' | 'onsite')[] | null;
  preferredLocations?:
    | {
        location: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional plans related to postgraduate education, specialization, or international study.
   */
  higherEducationGoal?: string | null;
  /**
   * Connect the profile to the most important skills currently being developed.
   */
  focusAreas?: (number | Skill)[] | null;
  /**
   * The professional email displayed publicly for recruiters and collaborators.
   */
  publicEmail: string;
  /**
   * Optional public phone number. Leave blank when you prefer email contact only.
   */
  phone?: string | null;
  socialLinks?:
    | {
        platform: 'linkedin' | 'github' | 'portfolio' | 'email' | 'youtube' | 'x' | 'instagram' | 'other';
        label: string;
        url: string;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  contactPreferences?:
    | {
        preference: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Select the primary professional profile photo from the Media collection.
   */
  profilePhoto?: (number | null) | Media;
  /**
   * Select the current downloadable resume from the Media collection.
   */
  resume?: (number | null) | Media;
  resumeLabel?: string | null;
  resumeLastUpdated?: string | null;
  /**
   * Optional professional introduction or portfolio walkthrough video.
   */
  introVideoURL?: string | null;
  professionalHighlights?:
    | {
        title: string;
        value: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  personalStrengths?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Mark this as the active profile used throughout the public portfolio.
   */
  featured?: boolean | null;
  heroBadge?: string | null;
  primaryCallToAction?: {
    label?: string | null;
    url?: string | null;
  };
  secondaryCallToAction?: {
    label?: string | null;
    url?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Review and manage messages submitted through the public SyedOS contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  phone?: string | null;
  subject: string;
  message: string;
  inquiryType: 'internship' | 'job' | 'freelance' | 'collaboration' | 'academic' | 'general' | 'other';
  preferredContactMethod?: ('email' | 'phone' | 'linkedin') | null;
  submissionStatus: 'new' | 'reviewed' | 'replied' | 'archived' | 'spam';
  priority: 'low' | 'normal' | 'high' | 'urgent';
  /**
   * Private notes visible only inside the administration dashboard.
   */
  adminNotes?: string | null;
  /**
   * Optional summary of the response or follow-up action taken.
   */
  responseSummary?: string | null;
  reviewedAt?: string | null;
  repliedAt?: string | null;
  /**
   * Assign the submission to an administrator for follow-up.
   */
  assignedTo?: (number | null) | User;
  sourcePage?: string | null;
  referrer?: string | null;
  userAgent?: string | null;
  ipAddress?: string | null;
  /**
   * Confirms that the sender agreed to be contacted regarding the submitted message.
   */
  consentAccepted: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'education';
        value: number | Education;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'profile';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  projectType?: T;
  developmentStatus?: T;
  shortDescription?: T;
  fullDescription?: T;
  technologies?:
    | T
    | {
        name?: T;
        category?: T;
        id?: T;
      };
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  responsibilities?:
    | T
    | {
        description?: T;
        id?: T;
      };
  githubURL?: T;
  liveURL?: T;
  documentationURL?: T;
  coverImageURL?: T;
  coverImageAlt?: T;
  featured?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  category?: T;
  proficiency?: T;
  proficiencyPercentage?: T;
  yearsOfExperience?: T;
  shortDescription?: T;
  iconName?: T;
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  relatedProjects?: T;
  learningSources?:
    | T
    | {
        title?: T;
        provider?: T;
        url?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        description?: T;
        id?: T;
      };
  featured?: T;
  displayOrder?: T;
  accentStyle?: T;
  badgeLabel?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  _order?: T;
  institution?: T;
  slug?: T;
  educationLevel?: T;
  qualification?: T;
  fieldOfStudy?: T;
  specialization?: T;
  university?: T;
  location?: T;
  institutionWebsite?: T;
  startYear?: T;
  endYear?: T;
  currentlyStudying?: T;
  expectedCompletion?: T;
  resultType?: T;
  result?: T;
  resultScale?: T;
  academicStanding?: T;
  summary?: T;
  coursework?:
    | T
    | {
        courseName?: T;
        description?: T;
        id?: T;
      };
  achievements?:
    | T
    | {
        title?: T;
        description?: T;
        year?: T;
        id?: T;
      };
  activities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  relatedSkills?: T;
  relatedProjects?: T;
  featured?: T;
  displayOrder?: T;
  logoPath?: T;
  logoAlt?: T;
  certificateURL?: T;
  badgeLabel?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  issuer?: T;
  certificationType?: T;
  issuerWebsite?: T;
  description?: T;
  credentialID?: T;
  credentialURL?: T;
  issueDate?: T;
  expiryDate?: T;
  doesNotExpire?: T;
  credentialStatus?: T;
  completionProgress?: T;
  estimatedHours?: T;
  score?: T;
  skillsCovered?: T;
  relatedProjects?: T;
  learningOutcomes?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  assessmentDetails?: T;
  instructors?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  featured?: T;
  displayOrder?: T;
  certificateImagePath?: T;
  certificateImageAlt?: T;
  issuerLogoPath?: T;
  issuerLogoAlt?: T;
  badgeLabel?: T;
  accentStyle?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  _order?: T;
  role?: T;
  slug?: T;
  organization?: T;
  experienceType?: T;
  location?: T;
  workMode?: T;
  organizationWebsite?: T;
  summary?: T;
  startDate?: T;
  endDate?: T;
  currentlyWorking?: T;
  durationLabel?: T;
  responsibilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  achievements?:
    | T
    | {
        title?: T;
        description?: T;
        metric?: T;
        id?: T;
      };
  technologies?: T;
  relatedProjects?: T;
  teamSize?: T;
  supervisor?:
    | T
    | {
        name?: T;
        role?: T;
        organization?: T;
      };
  certificateURL?: T;
  projectURL?: T;
  organizationLogoPath?: T;
  organizationLogoAlt?: T;
  supportingDocuments?:
    | T
    | {
        title?: T;
        url?: T;
        documentType?: T;
        id?: T;
      };
  featured?: T;
  displayOrder?: T;
  badgeLabel?: T;
  accentStyle?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  caption?: T;
  mediaType?: T;
  visibility?: T;
  featured?: T;
  displayOrder?: T;
  credit?: T;
  copyrightNotice?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  professionalTitle?: T;
  shortTitle?: T;
  headline?: T;
  shortBio?: T;
  fullBio?: T;
  location?: T;
  nationality?: T;
  languages?:
    | T
    | {
        language?: T;
        proficiency?: T;
        id?: T;
      };
  careerObjective?: T;
  careerInterests?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  preferredRoles?:
    | T
    | {
        role?: T;
        id?: T;
      };
  availabilityStatus?: T;
  preferredWorkModes?: T;
  preferredLocations?:
    | T
    | {
        location?: T;
        id?: T;
      };
  higherEducationGoal?: T;
  focusAreas?: T;
  publicEmail?: T;
  phone?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        featured?: T;
        id?: T;
      };
  contactPreferences?:
    | T
    | {
        preference?: T;
        id?: T;
      };
  profilePhoto?: T;
  resume?: T;
  resumeLabel?: T;
  resumeLastUpdated?: T;
  introVideoURL?: T;
  professionalHighlights?:
    | T
    | {
        title?: T;
        value?: T;
        description?: T;
        id?: T;
      };
  personalStrengths?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  featured?: T;
  heroBadge?: T;
  primaryCallToAction?:
    | T
    | {
        label?: T;
        url?: T;
      };
  secondaryCallToAction?:
    | T
    | {
        label?: T;
        url?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  phone?: T;
  subject?: T;
  message?: T;
  inquiryType?: T;
  preferredContactMethod?: T;
  submissionStatus?: T;
  priority?: T;
  adminNotes?: T;
  responseSummary?: T;
  reviewedAt?: T;
  repliedAt?: T;
  assignedTo?: T;
  sourcePage?: T;
  referrer?: T;
  userAgent?: T;
  ipAddress?: T;
  consentAccepted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}