/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    projects: Project;
    skills: Skill;
    education: Education;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Authorized administrators who can securely manage SyedOS content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The administrator’s professional display name.
   */
  name: string;
  /**
   * Controls access to protected SyedOS administration features.
   */
  role: 'super-admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Manage the projects displayed across the SyedOS professional portfolio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  /**
   * The professional name displayed on project cards and detail pages.
   */
  title: string;
  /**
   * Automatically generated from the project title. Example: syedai-assistant
   */
  slug: string;
  projectType: 'full-stack' | 'ai' | 'cloud-devops' | 'frontend' | 'backend' | 'academic' | 'other';
  developmentStatus: 'planning' | 'in-development' | 'completed' | 'maintained' | 'archived';
  /**
   * A concise project summary used on portfolio cards and previews.
   */
  shortDescription: string;
  /**
   * A detailed professional explanation of the project, its purpose, and its outcome.
   */
  fullDescription: string;
  technologies: {
    name: string;
    category: 'frontend' | 'backend' | 'database' | 'ai' | 'cloud' | 'devops' | 'testing' | 'tool' | 'other';
    id?: string | null;
  }[];
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  responsibilities?:
    | {
        description: string;
        id?: string | null;
      }[]
    | null;
  githubURL?: string | null;
  liveURL?: string | null;
  documentationURL?: string | null;
  /**
   * Temporary image path field. It will later be upgraded to Payload Media uploads.
   */
  coverImageURL?: string | null;
  /**
   * Describe the image for accessibility and search engines.
   */
  coverImageAlt?: string | null;
  /**
   * Display this project prominently on the homepage.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear before higher numbers.
   */
  displayOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage the technical skills displayed throughout the SyedOS professional portfolio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  _order?: string | null;
  /**
   * The professional technology or skill name displayed across the portfolio.
   */
  name: string;
  /**
   * Automatically generated from the skill name. Example: next-js
   */
  slug: string;
  category:
    | 'programming-language'
    | 'frontend'
    | 'backend'
    | 'database'
    | 'ai'
    | 'cloud'
    | 'devops'
    | 'testing'
    | 'cybersecurity'
    | 'tool'
    | 'soft-skill'
    | 'other';
  proficiency: 'beginner' | 'intermediate' | 'advanced' | 'professional';
  /**
   * Used for skill indicators. Enter a value from 0 to 100.
   */
  proficiencyPercentage: number;
  /**
   * Approximate practical experience with this skill.
   */
  yearsOfExperience?: number | null;
  /**
   * A concise explanation of how this skill is used in your work.
   */
  shortDescription: string;
  /**
   * Optional icon identifier, such as nextjs, typescript, docker, or postgres.
   */
  iconName?: string | null;
  capabilities?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Connect this skill to projects that demonstrate practical experience.
   */
  relatedProjects?: (number | Project)[] | null;
  learningSources?:
    | {
        title: string;
        provider?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display this skill prominently on the homepage or skills overview.
   */
  featured?: boolean | null;
  /**
   * Lower values appear before higher values.
   */
  displayOrder: number;
  /**
   * Controls the visual accent used for this skill in the portfolio.
   */
  accentStyle?: ('blue' | 'cyan' | 'teal' | 'violet' | 'amber' | 'emerald') | null;
  /**
   * Examples: Core Skill, Currently Learning, Certified, or Advanced.
   */
  badgeLabel?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage academic qualifications, institutions, achievements, coursework, and education details displayed on SyedOS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: number;
  _order?: string | null;
  /**
   * Enter the complete official name of the school, college, university, or training institution.
   */
  institution: string;
  /**
   * Automatically generated from the qualification and institution.
   */
  slug: string;
  educationLevel:
    | 'secondary-school'
    | 'higher-secondary'
    | 'diploma'
    | 'undergraduate'
    | 'postgraduate'
    | 'doctorate'
    | 'professional-certification'
    | 'other';
  qualification: string;
  fieldOfStudy?: string | null;
  /**
   * Optional specialization, concentration, branch, or major.
   */
  specialization?: string | null;
  /**
   * Enter the university name when the institution is an affiliated college.
   */
  university?: string | null;
  location?: string | null;
  institutionWebsite?: string | null;
  startYear: number;
  endYear?: number | null;
  /**
   * Enable this when the qualification is still in progress.
   */
  currentlyStudying?: boolean | null;
  expectedCompletion?: string | null;
  resultType?: ('cgpa' | 'gpa' | 'percentage' | 'grade' | 'pass' | 'not-applicable') | null;
  result?: string | null;
  /**
   * Optional grading scale used by the institution.
   */
  resultScale?: string | null;
  academicStanding?:
    ('distinction' | 'first-class' | 'second-class' | 'pass' | 'in-progress' | 'not-applicable') | null;
  /**
   * Explain the programme, academic focus, practical work, and its relevance to your professional goals.
   */
  summary: string;
  coursework?:
    | {
        courseName: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  achievements?:
    | {
        title: string;
        description?: string | null;
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  activities?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Connect this education record to relevant technical and professional skills.
   */
  relatedSkills?: (number | Skill)[] | null;
  /**
   * Connect academic projects completed during this qualification.
   */
  relatedProjects?: (number | Project)[] | null;
  /**
   * Feature this qualification prominently on the portfolio.
   */
  featured?: boolean | null;
  /**
   * Lower values appear before higher values.
   */
  displayOrder: number;
  logoPath?: string | null;
  /**
   * Describe the logo for accessibility and search engines.
   */
  logoAlt?: string | null;
  /**
   * Optional public URL for the certificate, marks memo, credential, or verification page.
   */
  certificateURL?: string | null;
  badgeLabel?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'education';
        value: number | Education;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  projectType?: T;
  developmentStatus?: T;
  shortDescription?: T;
  fullDescription?: T;
  technologies?:
    | T
    | {
        name?: T;
        category?: T;
        id?: T;
      };
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  responsibilities?:
    | T
    | {
        description?: T;
        id?: T;
      };
  githubURL?: T;
  liveURL?: T;
  documentationURL?: T;
  coverImageURL?: T;
  coverImageAlt?: T;
  featured?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  category?: T;
  proficiency?: T;
  proficiencyPercentage?: T;
  yearsOfExperience?: T;
  shortDescription?: T;
  iconName?: T;
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  relatedProjects?: T;
  learningSources?:
    | T
    | {
        title?: T;
        provider?: T;
        url?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        description?: T;
        id?: T;
      };
  featured?: T;
  displayOrder?: T;
  accentStyle?: T;
  badgeLabel?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  _order?: T;
  institution?: T;
  slug?: T;
  educationLevel?: T;
  qualification?: T;
  fieldOfStudy?: T;
  specialization?: T;
  university?: T;
  location?: T;
  institutionWebsite?: T;
  startYear?: T;
  endYear?: T;
  currentlyStudying?: T;
  expectedCompletion?: T;
  resultType?: T;
  result?: T;
  resultScale?: T;
  academicStanding?: T;
  summary?: T;
  coursework?:
    | T
    | {
        courseName?: T;
        description?: T;
        id?: T;
      };
  achievements?:
    | T
    | {
        title?: T;
        description?: T;
        year?: T;
        id?: T;
      };
  activities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  relatedSkills?: T;
  relatedProjects?: T;
  featured?: T;
  displayOrder?: T;
  logoPath?: T;
  logoAlt?: T;
  certificateURL?: T;
  badgeLabel?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}